nombre = input("Ingresa tu nombre: ")
apellido = input("Ingresa tu apellido: ")
edad = input("Ingresa tu edad: ")
ciudad = input("Ingresa tu ciudad: ")
pais = input("Ingresa tu país: ")

print("Nombre:", nombre)
print("Apellido:", apellido)
print("Edad:", edad)
print("Ciudad:", ciudad)
print("País:", pais)    